---
- name: Main Playbook
  hosts: all

  tasks:
    - name: Installation
      tags: install
      block:
        - name: Ping
          ansible.builtin.ping:

        - name: Import Redis key
          ansible.builtin.rpm_key:
            state: present
            key: https://packages.redis.io/gpg
          become: true

        - name: Install Redis repository
          ansible.builtin.yum_repository:
            name: Redis
            description: Redis repository
            baseurl: http://packages.redis.io/rpm/rhel9
            enabled: 1
            gpgcheck: 1
          become: true

        - name: Install epel-release
          ansible.builtin.dnf:
            state: present
            name: epel-release
          become: true

        - name: Install Redis Stack
          ansible.builtin.dnf:
            state: present
            name: redis-stack-server
          become: true

    - name: Primary Service
      tags: setup-primary
      block:
        - name: Ping
          ansible.builtin.ping:

        - name: Copy server.conf
          ansible.builtin.copy:
            src: ../server-primary.conf
            dest: /etc/server.conf
            owner: root
            group: root
            mode: 0644
          become: true

        - name: Start server
          ansible.builtin.shell:
            cmd: /usr/bin/redis-stack-server /etc/server.conf --protected-mode no --daemonize yes
          become: true

    - name: Replica Service
      tags: setup-replica
      block:
        - name: Ping
          ansible.builtin.ping:

        - name: Copy server.conf
          ansible.builtin.copy:
            src: ../server-replica.conf
            dest: /etc/server.conf
            owner: root
            group: root
            mode: 0644
          become: true

        - name: Start server
          ansible.builtin.shell:
            cmd: /usr/bin/redis-stack-server /etc/server.conf --protected-mode no --daemonize yes
          become: true

    - name: Sentinel Service
      tags: setup-sentinel
      block:
        - name: Ping
          ansible.builtin.ping:

        - name: Copy sentinel.conf
          ansible.builtin.copy:
            src: ../sentinel.conf
            dest: /etc/sentinel.conf
            owner: root
            group: root
            mode: 0644
          become: true

        - name: Start sentinel
          ansible.builtin.shell:
            cmd: /usr/bin/redis-sentinel /etc/sentinel.conf --protected-mode no --daemonize yes
          become: true

    - name: Create sentinel template
      tags: sentinel-template
      block:
        - name: Master IP
          become: yes
          ansible.builtin.shell: "ip address | grep -E -o 'inet [0-9.]+' | awk '{print $2}' | grep -v 127.0.0.1"
          register: master_ip

        - name: Create sentinel.conf
          become: yes
          vars:
            master_ip_address: "{{ master_ip.stdout }}"
          ansible.builtin.template:
            src: ../templates/sentinel.cnf.j2
            dest: /etc/sentinel.conf
    
    - name: Create Primary server template
      tags: primary-template
      block:
        - name: Create Primary server.conf
          ansible.builtin.template:
            src: ../templates/primary-server.cnf.j2
            dest: ./server-primary.conf
    
    - name: Create Replica server template
      tags: replica-template
      block:
        - name: Master IP
          become: yes
          ansible.builtin.shell: "ip address | grep -E -o 'inet [0-9.]+' | awk '{print $2}' | grep -v 127.0.0.1"
          register: master_ip

        - name: Create Replica server.conf
          ansible.builtin.template:
            src: ../templates/replica-server.cnf.j2
            dest: ./server-replica.conf
