---
- name: Template Playbook
  hosts: localhost

  tasks:
    - name: Create sentinel template
      tags: sentinel-template
      block:
        - name: Create sentinel.conf
          ansible.builtin.template:
            src: ../templates/sentinel.cnf.j2
            dest: ../sentinel.conf
    
    - name: Create Primary server template
      tags: primary-template
      block:
        - name: Create Primary server.conf
          ansible.builtin.template:
            src: ../templates/primary-server.cnf.j2
            dest: ../server-primary.conf
    
    - name: Create Replica server template
      tags: replica-template
      block:
        - name: Create Replica server.conf
          ansible.builtin.template:
            src: ../templates/replica-server.cnf.j2
            dest: ../server-replica.conf
